AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Inventory App

Parameters:
    AppName:
        Type: String
        Default: inventory-app
        Description: Application name
    Environment:
        Type: String
        Description: Define the runtime environment for the application

Globals:
    Function:
        Architectures:
            - arm64
        Runtime: nodejs22.x
        CodeUri: .
        Timeout: 60
        Environment:
            Variables:
                REGION: !Sub ${AWS::Region}
                ENVIRONMENT: !Ref Environment

Resources:
    InventoryAppApiGw:
        Type: AWS::Serverless::Api
        Properties:
            Name: !Sub ${Environment}-${AppName}-api
            Description: API Gateway for InventoryApp Endpoints
            StageName: !Ref Environment
            Cors:
                AllowMethods: "'POST,GET,PATCH,DELETE,HEAD,OPTIONS'"
                AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                AllowOrigin: "'*'"

    CategoriesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Environment}-${AppName}-categories-table
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH

    ProductsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Environment}-${AppName}-products-table
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
            AttributeDefinitions:
                - AttributeName: sku
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
                - AttributeName: category
                  AttributeType: S
            KeySchema:
                - AttributeName: sku
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: CategoryIndex
                  KeySchema:
                      - AttributeName: category
                        KeyType: HASH
                      - AttributeName: name
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL

    CreateProductFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Environment}-${AppName}-create-product
            Description: Create product record in database
            Handler: src/handlers/v1/products/createProduct.handler
            AutoPublishAlias: live
            # Environments:
            #     TABLE_NAME: !GetAtt ProductsTable.TableName
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref InventoryAppApiGw
                        Path: /v1/products
                        Method: POST
                        TimeoutInMillis: 60000
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ProductsTable

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Format: esm
                OutExtension:
                    - .js=.mjs
                Minify: true
                Target: es2022
                Sourcemap: false
                Banner:
                    - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
                EntryPoints:
                    - src/handlers/v1/products/createProduct.ts

Outputs:
    InventoryAppApiGw:
        Description: 'API Gateway endpoint URL'
        Value: !Sub 'https://${InventoryAppApiGw}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'
    CreateProductFunctionArn:
        Description: 'Create Product Lambda Function ARN'
        Value: !GetAtt CreateProductFunction.Arn
