AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Inventory App

Parameters:
    AppName:
        Type: String
        Default: inventory-app
        Description: Application name
    Environment:
        Type: String
        Description: Define the runtime environment for the application

Globals:
    Function:
        Architectures:
            - arm64
        Runtime: nodejs22.x
        CodeUri: .
        Timeout: 60
        Environment:
            Variables:
                REGION: !Sub ${AWS::Region}
                ENVIRONMENT: !Ref Environment

Resources:
    CategoriesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Environment}-${AppName}-categories-table
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH

    ProductsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Environment}-${AppName}-products-table
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
            AttributeDefinitions:
                - AttributeName: sku
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
                - AttributeName: category
                  AttributeType: S
            KeySchema:
                - AttributeName: sku
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: CategoryIndex
                  KeySchema:
                      - AttributeName: category
                        KeyType: HASH
                      - AttributeName: name
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL

    # CreateProduct:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         FunctionName: !Sub ${Environment}-${AppName}
    #         Handler: src/handlers/addItem.handler
    #         Events:
    #             HelloWorld:
    #                 Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
    #                 Properties:
    #                     Path: /hello
    #                     Method: get
    #     Metadata: # Manage esbuild properties
    #         BuildMethod: esbuild
    #         BuildProperties:
    #             Minify: true
    #             Target: 'es2020'
    #             Sourcemap: true
    #             EntryPoints:
    #                 - app.ts

Outputs:
    # HelloWorldApi:
    #     Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    #     Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    # HelloWorldFunction:
    #     Description: 'Hello World Lambda Function ARN'
    #     Value: !GetAtt HelloWorldFunction.Arn
