# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "book-tracker-app-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "book-tracker-app-dev"
region = "us-east-1"
parameter_overrides = "AppName=\"book-tracker-app\" AllowOrigin=\"http://localhost:3000\" AllowCredentials=\"'true'\" Environment=\"dev\" BookHandlersPath=\"src/handlers/v1/books\""
image_repositories = []
stack_name = "book-tracker-app-dev"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
stack_name = "book-tracker-app-dev"
resolve_s3 = true
s3_prefix = "book-tracker-app-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"book-tracker-app\" AllowOrigin=\"http://localhost:3000\" AllowCredentials=\"'true'\" Environment=\"dev\" BookHandlersPath=\"src/handlers/v1/books\""
image_repositories = []

[staging.deploy.parameters]
stack_name = "book-tracker-app-staging"
resolve_s3 = true
s3_prefix = "book-tracker-app-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"book-tracker-app\" AllowOrigin=\"https://staging.therialniels-dev.com\" AllowCredentials=\"'true'\" Environment=\"staging\" BookHandlersPath=\"src/handlers/v1/books\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "book-tracker-app-prod"
resolve_s3 = true
s3_prefix = "book-tracker-app-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"book-tracker-app\" AllowOrigin=\"https://therialniels-dev.com\" AllowCredentials=\"'true'\" Environment=\"prod\" BookHandlersPath=\"src/handlers/v1/books\""
image_repositories = []
