AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    power-of-math

    Sample SAM Template for power-of-math application

Globals:
    Function:
        Timeout: 3

Resources:
    PowerOfMathDatabase:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: power-of-math
            PrimaryKey:
                Name: id
                Type: String

    PowerOfMathFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: power-of-math
            CodeUri: power-of-math/
            Handler: app.handler
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    TABLE_NAME: !Ref PowerOfMathDatabase
            Policies:
                Statement:
                    Sid: DynamoDBCrud
                    Effect: Allow
                    Action:
                        - dynamodb:PutItem
                        - dynamodb:DeleteItem
                        - dynamodb:GetItem
                        - dynamodb:Scan
                        - dynamodb:Query
                        - dynamodb:UpdateItem
                    Resource: !GetAtt PowerOfMathDatabase.Arn
            Events:
                PowerOfMath:
                    Type: Api
                    Properties:
                        Path: /
                        Method: post

Outputs:
    PowerOfMathApi:
        Description: 'API Gateway endpoint URL for Staging stage for Power of Math function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/staging/'
    PowerOfMathFunction:
        Description: 'Power of Math Lambda Function ARN'
        Value: !GetAtt PowerOfMathFunction.Arn
    PowerOfMathFunctionIamRole:
        Description: 'Implicit IAM Role created for Power of Math function'
        Value: !GetAtt PowerOfMathFunctionRole.Arn
