AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    power-of-math

    Sample SAM Template for power-of-math application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    PowerOfMathDatabase:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: power-of-math
            PrimaryKey:
                Name: id
                Type: Number

    PowerOfMathFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: power-of-math
            CodeUri: power-of-math/
            Handler: app.handler
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    TABLE_NAME: !Ref PowerOfMathDatabase
            Events:
                PowerOfMath:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: post

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    PowerOfMathApi:
        Description: 'API Gateway endpoint URL for Staging stage for Power of Math function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/staging/'
    PowerOfMathFunction:
        Description: 'Power of Math Lambda Function ARN'
        Value: !GetAtt PowerOfMathFunction.Arn
    PowerOfMathFunctionIamRole:
        Description: 'Implicit IAM Role created for Power of Math function'
        Value: !GetAtt PowerOfMathFunctionRole.Arn
