AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    text-to-audio

    Sample SAM Template for text-to-audio

Globals:
    Function:
        Timeout: 60

Parameters:
    StageName:
        Type: String
        Default: staging

Resources:
    ConvertTextBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub 'jdp-${AWS::StackName}-bucket'
            PublicAccessBlockConfiguration:
                BlockPublicPolicy: false

    ConvertTextBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ConvertTextBucket
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    Action:
                        - s3:PutObject
                    Effect: Allow
                    Resource: !Join
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref ConvertTextBucket
                          - /*
                    Principal: '*'

    ConvertTextApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref StageName
            Cors:
                AllowMethods: "'POST,OPTIONS'"
                AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                AllowOrigin: "'*'"

    ConvertTextFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: convertText.handler
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    BUCKET_NAME: !Ref ConvertTextBucket
            Policies:
                - AmazonPollyFullAccess
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action: s3:GetObject
                        Resource: !Sub '${ConvertTextBucket.Arn}/*'

            Events:
                ConvertText:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ConvertTextApi
                        Path: /convert-text
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - convertText.ts

Outputs:
    ConvertTextBucket:
        Description: 'Convert Text Bucket ARN'
        Value: !GetAtt ConvertTextBucket.Arn
    ConvertTextApi:
        Description: 'API Gateway endpoint URL'
        Value: !Sub 'https://${ConvertTextApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/convert-text'
    ConvertTextFunction:
        Description: 'Convert Text Lambda Function ARN'
        Value: !GetAtt ConvertTextFunction.Arn
    ConvertTextFunctionIamRole:
        Description: 'Implicit IAM Role created for Convert Text function'
        Value: !GetAtt ConvertTextFunctionRole.Arn
